### ISSUE TITLE
ImportError for py3.6 on macos 10.12.3

### ISSUE THREAD

**Issue by everdark** [ibayer/fastFM#100]
When trying `from fastFM import als` I got the following error:

```py
ImportError: dlopen(/usr/local/lib/python3.6/site-packages/ffm.cpython-36m-darwin.so, 2): Symbol not found: _cs_di_norm
  Referenced from: /usr/local/lib/python3.6/site-packages/ffm.cpython-36m-darwin.so
  Expected in: flat namespace
 in /usr/local/lib/python3.6/site-packages/ffm.cpython-36m-darwin.so
```

I've seem similar issue for other people using other platform/version but not solution as well.
I installed the package with `pip3 install fastFM` without any error.

My system info:
```
macOS 10.12.3
Python 3.6.0
```

**Comment by ibayer** [comment]
This might be because we currently don't provide python 3.6 wheels and the source install fails.
Creating the wheels should be possible. ` _cs_di_norm` indicates that the cython build didn't work properly and the CXSparse dependency hasn't been compiled properly.

**Comment by everdark** [comment]
I try instead use a virtualenv with py 3.5. everything is fine now.
