### ISSUE TITLE
cpp cython-wrapper update to header only

### ISSUE THREAD

**Issue by ibayer** [ibayer/fastFM#107]
- [ ] update fastFM-core2 subrepository to latest commit.
- [ ] adapt setup.py to the new header only lib 

only the files in 

```
https://github.com/ibayer/fastFM-core2/tree/api/fastFM
```
+ Eigen 
should now be needed for the cython wrapper 

@caos21
I have just merged the header only refactoring https://github.com/ibayer/fastFM-core2/pull/30 .
Are you willing to take another shot add the cython-wrapper? I hope the build process is now much simpler (still not easy) without the static build and musl stuff. I'm not sure about how to include the Eigen files yet.

**Comment by ibayer** [comment]
moving to fastFM-core2 repo https://github.com/ibayer/fastFM-core2/issues/33

**Comment by ibayer** [comment]
depends on https://github.com/ibayer/fastFM-core2/issues/34

**Comment by dselivanov** [comment]
@ibayer `fastFM-core2` is not available now?
