### ISSUE TITLE
Symbol not found: _PyBytes_Type error running nosetests

### ISSUE THREAD

**Issue by colemast** [ibayer/fastFM#11]
I thought I had managed to get this all working on a Mac until I ran the nose tests for the python wrapper. I get the following error

```
======================================================================
ERROR: Failure: ImportError (dlopen(/Users/mellypang/eduvee-data/fastfm/fastFM/ffm.so, 2): Symbol not found: _PyBytes_Type
  Referenced from: /Users/mellypang/eduvee-data/fastfm/fastFM/ffm.so
  Expected in: dynamic lookup
)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mellypang/anaconda/envs/fastfm/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/mellypang/anaconda/envs/fastfm/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/mellypang/anaconda/envs/fastfm/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/mellypang/eduvee-data/fastfm/fastFM/fastFM/tests/test_als.py", line 7, in <module>
    from fastFM import als
  File "/Users/mellypang/eduvee-data/fastfm/fastFM/fastFM/als.py", line 6, in <module>
    from base import FactorizationMachine, BaseFMClassifier,\
  File "/Users/mellypang/eduvee-data/fastfm/fastFM/fastFM/base.py", line 5, in <module>
    import ffm
ImportError: dlopen(/Users/mellypang/eduvee-data/fastfm/fastFM/ffm.so, 2): Symbol not found: _PyBytes_Type
  Referenced from: /Users/mellypang/eduvee-data/fastfm/fastFM/ffm.so
  Expected in: dynamic lookup
```

All the other steps seem to run fine. Fastfm-core compiles and the tests pass, and the pip freeze contains  the fastfm package

```
backports.ssl-match-hostname==3.4.0.2
certifi==2015.4.28
Cython==0.22
-e git+https://github.com/ibayer/fastFM.git@15b3a451978315d298348778ddc9de11b9e05f8f#egg=fastFM-master
functools32==3.2.3.post2
gnureadline==6.3.3
ipython==3.2.1
Jinja2==2.8
jsonschema==2.5.1
MarkupSafe==0.23
mistune==0.7
numpy==1.9.1
pandas==0.15.2
ptyprocess==0.5
Pygments==2.0.2
python-dateutil==2.4.2
pytz==2015.4
pyzmq==14.7.0
scikit-learn==0.16.0
scipy==0.15.1
six==1.9.0
terminado==0.5
tornado==4.2.1
```
Anyone else encountered a similar issue

**Comment by ibayer** [comment]
@colemast 
You might miss the Python dev header. Would be ``sudo apt-get install build-essential python-dev python-setuptools`` on linux. I have pushed the OSX fixes to fastFM. I hope this helps to get more OSX user to try.

**Comment by colemast** [comment]
Thanks for the pointer - it was that. I had the Python dev header installed but as I am using Anaconda the setup.py was looking in the wrong place. I added /Users/colemast/anaconda/envs/fastfm/include/ into the include_dirs and it is all working now so I have a fully functioning OS X version.

Thanks so much for your work on this. I have used libFM for a while now, but to have it in my Python toolkit is awesome.

I'm happy to try and write up what I had to do to get this to work on OS X if you think that would be useful.

**Comment by ibayer** [comment]
@colemast 
Sure, it would be great if you could improve the README. Just fork & edit or post you changes here. The missing Python dev headers effects all OS's and should probably be added in the build instructions.

**Comment by chunguo** [comment]
I'm having the same issue with cblas.h. I've tried adding the directory where it is located to the include_dirs section in the setup.py. But the compiler still complains that it cannot find cblas.h. Did I add it to the wrong place?

This is an exerpt from my modified setup.py:

`ext_modules = [
    Extension('ffm', ['fastFM/ffm.pyx'],
              libraries=['m', 'fastfm', 'cxsparse', 'blas'],
              library_dirs=['fastFM/', 'fastFM-core/bin/',
                            'fastFM-core/externals/CXSparse/Lib/'],
              include_dirs=['fastFM/', 'fastFM-core/include/',
                            'fastFM-core/externals/CXSparse/Include/',
                            '/opt/pagerank/recommendation/anaconda2/include/',
              numpy.get_include()])]`
