### ISSUE TITLE
incompatibility with NumPy >= 1.13

### ISSUE THREAD

**Issue by lucidfrontier45** [ibayer/fastFM#118]
https://docs.scipy.org/doc/numpy-1.13.0/release.html#deprecationwarning-to-error

In NumPy 1.13, negative boolean will cause error.

For example this line will fail
https://github.com/ibayer/fastFM/blob/master/fastFM/als.py#L191

I will submit PR and since this is a very serious issue, can you update PyPI's package after merge?

**Comment by ibayer** [comment]
I think it's already in master, at least I remember changing it in a few places.

**Comment by ibayer** [comment]
You link points to

``` python
y_train[~i_class1] = 1
```
which is fine or? We change `-` to `~` some time ago.

**Comment by lucidfrontier45** [comment]
@ibayer 

My bad. I looked my screen from a distance and confused "~" with "-".
It's OK now. When fill you publish to PyPI?

**Comment by ibayer** [comment]
I have just released 0.2.10 which should be compatible with recent numpy versions.
