### ISSUE TITLE
Assertion Error 

### ISSUE THREAD

**Issue by sriram-ramanathan** [ibayer/fastFM#120]
I am getting the following error while fitting the model.

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-76-38ee56fd32d5> in <module>()
      1 #from fastFM import als
      2 fm = sgd.FMClassification(n_iter=1000, init_stdev=0.1, rank=3)
----> 3 fm.fit(X_train,pd.Series(yy).values)

/usr/local/lib/python2.7/dist-packages/fastFM/sgd.pyc in fit(self, X, y)
    188         X = check_array(X, accept_sparse="csc", dtype=np.float64)
    189 
--> 190         self.w0_, self.w_, self.V_ = ffm.ffm_sgd_fit(self, X, y)
    191         return self

fastFM/ffm.pyx in ffm.ffm_sgd_fit (fastFM/ffm.c:4312)()

AssertionError:

**Comment by ibayer** [comment]
You need to make sure that `X` is a scipy csc_matrix.

**Comment by ibayer** [comment]
Please reopen is you still have questions.
