### ISSUE TITLE
No coordinate descent solver available

### ISSUE THREAD

**Issue by christian96l** [ibayer/fastFM#160]
In the README.rst it says:

> fastFM provides stochastic gradient descent (SGD) and coordinate descent (CD) optimization routines as well as Markov Chain Monte Carlo (MCMC) for Bayesian inference.

But I could only find SGD, ALS and MCMC solvers in the documentation. Is there no CD solver yet?

**Comment by ibayer** [comment]
@christian96l 

I guess the README is a bit unclear at this point. CD and ALS are actually the same solver.
BTW our rewrite supports CD regression https://github.com/palaimon/fastfm2. So this might me an alternative if that's all you need.
