### ISSUE TITLE
Issues compiling with OS X El Capitan (10.11.3)

### ISSUE THREAD

**Issue by merrellb** [ibayer/fastFM#32]
I've tried both GCC 5.3.0 and Apple LLVM version 7.0.2 and get the same results:

```
$ make
( cd fastFM-core ; /Applications/Xcode.app/Contents/Developer/usr/bin/make lib )
( cd src ; /Applications/Xcode.app/Contents/Developer/usr/bin/make lib )
gcc -std=c99 -fPIC -g -Wall -O3 -I/include -I./src -I../externals/CXSparse/Include -I   -c -o kmath.o kmath.c
kmath.c:23:9: warning: 'M_SQRT2' macro redefined [-Wmacro-redefined]
#define M_SQRT2 1.41421356237309504880  /*-- sqrt(2) */
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/math.h:709:9: note: 
      previous definition is here
#define M_SQRT2     1.41421356237309504880168872420969808   /* sqrt(2)        */
        ^
1 warning generated.
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [kmath.o] Error 1
make[1]: *** [lib] Error 2
make: *** [all] Error 2
```

**Comment by ibayer** [comment]
Don't know what's up but I suspect a local issue. OSX build on Travis is working and
it should work on El Capitan see #13. 

You could have a look at: https://travis-ci.org/ibayer/fastFM/jobs/104413845 
for an example on how to setup a working build environment.

I recommend to clone add build fastFM-core first. Please cp commands and output for all steps here and
maybe someone else can help.

**Comment by chezou** [comment]
This is typical error. You have to set `CC=/usr/bin/gcc` or some other c compiler like gcc installed by homebrew.

**Comment by merrellb** [comment]
I've made some progress on this.  I've modified the Makefile to find the necessary header files installed by homebrew:
```
CFLAGS += -I/usr/local/opt/openblas//include
CFLAGS += -I/usr/local/opt/argp-standalone//include
```
and using the following make options to use libstdc++ instead of the default libc++:
```
make -stdlib=libstdc++ -lstdc++ cli
```
However I am still running into some issues and the new binary wheel file will hopefully make this all moot.

**Comment by melqkiades** [comment]
Where you able to solve the issue? I'm facing the same. If so, could you give me the steps you followed to fix it? Thanks
