### ISSUE TITLE
Question:Using Custom Dataset

### ISSUE THREAD

**Issue by farimahfanaei** [ibayer/fastFM#42]
1.I am about to to use a customized data set in fastFm. Data is a collection of many messages (text content) and subjects, one of the **features** is **key words array** (array of few words) and the other feature is the **subjects**,as both of the features are textual kinds,I was wondering how to use fastFM with such data set?
2. in case I use corresponding unique IDs for each single word and subject which means I'll have an array of **integer values** for Keywords feature, do you think if "**OneHotEncoder**" can be any helpful for changing such string values and make them useful for fastFm?

**Comment by ibayer** [comment]
@farimahfanaei 
Using One-Hot encoding sounds like a reasonable idea.  I would encourage you to just try things out and see for yourself what works for you particular problem and dataset.
