### ISSUE TITLE
Cannot clone object FMClassification

### ISSUE THREAD

**Issue by prophile** [ibayer/fastFM#44]
I receive this error:

```
RuntimeError: Cannot clone object FMClassification(init_stdev=0.1, l2_reg=None, l2_reg_V=0.1, l2_reg_w=0.1,
         n_iter=100, random_state=123, rank=8), as the constructor does not seem to set parameter l2_reg_V
```

when using FMClassification with `cross_val_score`.

**Comment by ibayer** [comment]
Please provide [Short, Self Contained, Correct (Compilable), Example](http://www.sscce.org/) so that we don't have to guess what you are trying to do.
