### ISSUE TITLE
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by mpearmain** [ibayer/fastFM#6]
I follow all the build instructions and have all requirements upto date, however when i 'make' 
i get the following error

/usr/bin/ld: cannot find -lgsl
/usr/bin/ld: cannot find -lgslcblas
collect2: error: ld returned 1 exit status
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
make: *** [all] Error 1

**Comment by ibayer** [comment]
Hi mpearmain,
from which folder are you running `make`? If you are compiling the
tests in `fastFM-core` you need to also install `sudo apt-get install libgsl0-dev`.
Its listed as optional dependency in the `fastFM-core` README.

**Comment by mpearmain** [comment]
thanks this solved the build issue
