### ISSUE TITLE
Train rmse of each iter for mcmc

### ISSUE THREAD

**Issue by Vimos** [ibayer/fastFM#64]
In libfm, there's log on train rmse and test rmse. How to compute train rmse when using mcmc?

`        self.w0_, self.w_, self.V_ = coef`

I saw this line in mcmc, which means I may compute the prediction on train, is there any plan on offering the config of computing train rmse?

The following way does not work, 
fm = mcmc.FMRegression(n_iter=0, init_stdev=0.1, rank=2) 
for i in range(1, n_iter):
            y_pred = fm.fit_predict(X_train, y_train, X_test, n_more_iter=step_size)
            rmse_train.append(np.sqrt(mean_squared_error(fm.predict(X_train), y_train)))
            rmse_test.append(np.sqrt(mean_squared_error(fm.predict(X_test), y_test)))  
logging.info(rmse_train)

which gives an error
`
AttributeError: 'FMRegression' object has no attribute 'w0_'
`

**Comment by ibayer** [comment]
I don't see the problem your approach should work.
You don't need to predict twice on (X_train)

```Python
fm = mcmc.FMRegression(n_iter=0, init_stdev=0.1, rank=2)
for i in range(1, n_iter):
   y_pred = fm.fit_predict(X_train, y_train, X_test, n_more_iter=step_size)
   rmse_train.append(np.sqrt(mean_squared_error(fm.predict(X_train), y_train)))
   rmse_test.append(np.sqrt(mean_squared_error(y_pred, y_test)))
```

Can you provide a small example that I can run?

**Comment by Vimos** [comment]
Warm start checking now is not well formed, due to the n_more_iter parameter.
To fix this, I suggest add the following check

    -        if n_more_iter > 0:
    +        if n_more_iter > 0 and self.n_iter != 0:
    
And move the n_iter update to the end of the function

If I start model with n_iter=0, it is now working.

**Comment by ibayer** [comment]
@Vimos 
Thanks for reporting this. Example would be great or just open a PR request with your
change.

**Comment by Vimos** [comment]
Now I am clear with the problem,
before using

     y_pred = fm.fit_predict(X_train, y_train, X_test, n_more_iter=step_size)

one should call 
        
     fm.fit_predict(X_train, y_train, X_test)

at first.

Else the warm start checking error will show up.

**Comment by ibayer** [comment]
@Vimos 
Please reopen if you think we should change the documentation.
