### ISSUE TITLE
Problem running MCMC example code

### ISSUE THREAD

**Issue by santteegt** [ibayer/fastFM#66]
Hi,

I'm trying to run your example code for the MCMC method. I downloaded the 100k-Movielens dataset and generate the lightsvm data format of u1.base and u1.test files using [srendle/libFM](https://github.com/srendle/libfm) script. But I'm getting the following error when trying to load the data with sklearn.datasets.load_svmlight_file:

`ValueError: Feature indices in SVMlight/LibSVM data file should be sorted and unique.`

I tried re-sorting rows by the index id of both features (user id, item id), but nothing happened. I'm sure that it's some kind of a silly error I'm commiting Could you help me with this issue, please?. Maybe can I find the files you use in the example to check the format?

Thanks.

Regards.

**Comment by chezou** [comment]
[libsvm](https://www.csie.ntu.edu.tw/~cjlin/libsvm/) has check tool named `tools/checkdata.py`. It might help you to validate generated file.

**Comment by santteegt** [comment]
Thanks. The script I was using is not working properly. Solved it!
