### ISSUE TITLE
Feature extraction from fastFM

### ISSUE THREAD

**Issue by vladimirlitvinyuk** [ibayer/fastFM#67]
Hello
Thanks for a great tool. Could you, please, ask a couple of questions on its functionality?
Is it somehow possible:
- to extract weights/latent feature vectors from fastFM fitted model
- to make feature space transformation to latent feature space, using fitted fastFM model.

The interesting part of the task - not only to predict actual ratings/probabilities, but also get some information on products and clients clusters.

Thanks a lot in advance,
Best regards
Vladimir Litvinyuk

**Comment by ibayer** [comment]
Hi,
you can access the latent representation of the features easily after training the model.
```
fm = als.FMRegression()
fm.fit(X_train, y_train)
```
Its in the docs: http://ibayer.github.io/fastFM/api.html#module-fastFM.als
```
fm.w0 # (float) – bias term
fm.w # (float | array, shape = (n_features)) – Coefficients for linear combination.
fm.V # (float | array, shape = (rank_pair, n_features)) – Coefficients of second order factor matrix`
```
