### ISSUE TITLE
I get an error when I try to import it

### ISSUE THREAD

**Issue by tanql** [ibayer/fastFM#72]
"dlopen(/Users/tanle/Desktop/recommender/lib/python2.7/site-packages/ffm.so, 2): Symbol not found: _cs_di_norm
  Referenced from: /Users/tanle/Desktop/recommender/lib/python2.7/site-packages/ffm.so
  Expected in: flat namespace
 in /Users/tanle/Desktop/recommender/lib/python2.7/site-packages/ffm.so"

**Comment by ibayer** [comment]
You need to provide more information. This looks very much like a problem with you local setup.

**Comment by tanql** [comment]
I've installed it with pip install, and there were no error msg there. However, when I try to "from fastFM import als", I get that error msg. Im using macOS sierra

**Comment by rheras** [comment]
Hi all, thanks  for your posts, I'm using CentOS as well, having a similar error,
my error refers to cblas_ddot file, when importing ffm, as follows,
make compilation was not successful in the previous step, really I don't know how to preceed...
cheers.

$more ex1.py
from fastFM import als
fm = als.FMRegression(n_iter=1000, init_stdev=0.1, rank=2, l2_reg_w=0.1, l2_reg_V=0.5)
fm.fit(X_train, y_train)
y_pred = fm.predict(X_test)

[sams examples]$ python2.7 ex1.py
Traceback (most recent call last):
File "ex1.py", line 1, in
from fastFM import als
File "/usr/local/lib/python2.7/site-packages/fastFM/als.py", line 4, in
import ffm
_ImportError: /usr/local/lib/python2.7/site-packages/ffm.so: undefined symbol: cblas_ddot_

**Comment by Darinyazanr** [comment]
Using centOS 7: issue  
File "testFastFM.py", line 1, in <module>
    from fastFM import als
  File "/usr/lib64/python2.7/site-packages/fastFM/als.py", line 4, in <module>
    import ffm
ImportError: /usr/lib64/python2.7/site-packages/ffm.so: undefined symbol: cblas_daxpy

**Comment by ibayer** [comment]
Can you try a source install? You can find the necessary instructions in the README. Please report outputs for each step. I suspect that the C library has not been properly  compiled.

**Comment by Darinyazanr** [comment]
@ibayer Source install is works! thx very much! 
Could i use fastFM to my production if it really suitable for my project?

**Comment by ibayer** [comment]
@Darinyazanr thanks for the feedback.
fastFM is released under the BSD license. I think that should cover most use cases.

**Comment by ibayer** [comment]
I'm closing this as the new linux binary should fix the install issues.
