### ISSUE TITLE
number of processors / dataset size...

### ISSUE THREAD

**Issue by josepablog** [ibayer/fastFM#76]
Hello,

Do you have a sense of the size of the dataset that is tractable with FastFM? I am looking to do collaborative filtering with ~100 Million rows.  Would this library scale ?

Thanks,
Jose

**Comment by josepablog** [comment]
Another way to phrase the question is:

Does LibFM run in a single thread, or is computation parallel?

**Comment by ibayer** [comment]
The runtime is linear in the number of training samples (ALS & MCMC). You can use
figure 2 in [0] to get a very rough estimate of the runtime you can expect (but it really depends on the data set, your hardware etc.). You could also just sample 1 Million rows of your data run some experiments on it and estimate the cost for the full data.

libFM is currently only singe thread.

[0] http://jmlr.org/papers/volume17/15-355/15-355.pdf

**Comment by josepablog** [comment]
this is great! congratulations on the paper, btw :)
