### ISSUE TITLE
fm.fit_predict vs fm.predict

### ISSUE THREAD

**Issue by edmondja** [ibayer/fastFM#9]
Hello, 

I wanted to use fm.predict to have a fast prediction with MCMC FM, without using fit_predict.

Maybe i am wrong, but 
Yhat=fm.fit_predict(X_train, ytrain,X_test)
and
Yhat0=fm.predict(X_test)
(when executed after fit_predict)
should return the same thing right ?
However it is not the case. (even np.sort(Yhat) and np.sort(Yhat0) are different)

I tried to predict manually : 
X=X_test
V=np.transpose(fm.V_)
w=fm.w_
w0=fm.w0_
XV=X * V
R=np.square(XV)-X.multiply(X) * np.square(V)
Yhat1=(X*w+w0)+np.sum(R,axis=1)/2

And I have seen that Yhat1=Yhat0, so I think that the reason why fm.predict doesn't return the same thing as fm.fit_predict is that some parameters among w, w0, and V are not really those which are fitted with X_train and ytrain while using fm.fit_predict(X_train, ytrain,X_test).

Maybe I dont have understood how the lib works or maybe I don't have understood the true meaning of the function fit_predict, but it always gives me a better RMSE than fm.predict.

I have tried this :
Yhat2=fm.fit_predict(X_train[:1], ytrain[:1], X_test, n_more_iter=1)

But even it is fast to compute and similar to Yhat, it deteriorates the RMSE.

(And plzz find a solution to install the packages on osx)

I really hope my post is useful,

Thanks for that lib.

**Comment by ibayer** [comment]
Hi edmondja.
thanks for you feedback. You observations about the behaviour of  `predict()` for the `mcmc` module is
correct. This is however the nature of mcmc algorithms for nonlinear models. I still need to finish the documentation for this library but hopefully the sniped below is helpfully for you.

> (And plzz find a solution to install the packages on osx)

Sorry, I don't have the time to look into this at the moment. I'm not developing on OSX
myself but I would love to include the instructions on how to compile on OSX if someone figures out
how to do it.

**Comment by ibayer** [comment]
How to choose the right Solver.
-------------------------------

This section explains the trade off between the three solvers available in fastFM.
The following applies for both **classification** and **regression** tasks.

.. testcode::

    import fastFM.mcmc

- (+) least number of hyper parameters
- (+) automatic regularization
- (-) predictions need to be calculated at training time

`Note: The predict method of the mcmc model returns predictions based on only
the last draw of the model parameters. This evaluation is fast
but usually of low quality. Don't use mcmc if you need fast predictions!`

.. testcode::

    import fastFM.als

- (+) fast predictions
- (+) less hyper parameter then SGD
- (-) regularization must be specified

.. testcode::

    import fastFM.sgd

- (+) fast predictions
- (+) warm start can be used to iterate junks of a large dataset
- (-) regularization must be specified
- (-) highest number of hyper parameter (requires, `step_size`)

**Comment by edmondja** [comment]
Ok that's perfectly clear.

Thank you !
